<?php

namespace App\Docs;

use OpenApi\Attributes as OA;

class PatientDocs
{
    #[OA\Get(
        path: '/patients',
        summary: 'List patients (search, filter, sort, paginate)',
        description: 'Roles: admin, doctor, receptionist. Soft-deleted patients are never returned. The search parameter matches one word at a time against name, patient number, phone and email.',
        tags: ['Patients'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string', maxLength: 100)),
            new OA\Parameter(name: 'gender', in: 'query', schema: new OA\Schema(type: 'string', enum: ['male', 'female', 'other'])),
            new OA\Parameter(name: 'blood_group', in: 'query', schema: new OA\Schema(type: 'string', enum: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'])),
            new OA\Parameter(name: 'sort', in: 'query', description: 'Prefix with - for descending', schema: new OA\Schema(type: 'string', default: '-created_at', enum: ['created_at', '-created_at', 'last_name', '-last_name', 'date_of_birth', '-date_of_birth'])),
            new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, default: 1)),
            new OA\Parameter(name: 'per_page', in: 'query', description: 'Items per page (1 to 100)', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 15)),
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Paginated list',
                content: new OA\JsonContent(allOf: [
                    new OA\Schema(ref: '#/components/schemas/SuccessEnvelope'),
                    new OA\Schema(properties: [
                        new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/Patient')),
                        new OA\Property(property: 'meta', ref: '#/components/schemas/PaginationMeta'),
                    ]),
                ])
            ),
            new OA\Response(ref: '#/components/responses/Unauthenticated', response: 401),
            new OA\Response(ref: '#/components/responses/ValidationError', response: 422),
            new OA\Response(ref: '#/components/responses/TooManyRequests', response: 429),
        ]
    )]
    public function index(): void
    {
    }

    #[OA\Get(
        path: '/patients/{id}',
        summary: 'Get one patient',
        description: 'Roles: admin, doctor, receptionist.',
        tags: ['Patients'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer')),
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: 'The patient',
                content: new OA\JsonContent(allOf: [
                    new OA\Schema(ref: '#/components/schemas/SuccessEnvelope'),
                    new OA\Schema(properties: [
                        new OA\Property(property: 'data', ref: '#/components/schemas/Patient'),
                    ]),
                ])
            ),
            new OA\Response(ref: '#/components/responses/Unauthenticated', response: 401),
            new OA\Response(ref: '#/components/responses/NotFound', response: 404),
        ]
    )]
    public function show(): void
    {
    }

    #[OA\Post(
        path: '/patients',
        summary: 'Register a patient',
        description: 'Role: receptionist only. The patient_number is generated by the server and cannot be sent.',
        tags: ['Patients'],
        security: [['sanctum' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(allOf: [
                new OA\Schema(ref: '#/components/schemas/PatientInput'),
                new OA\Schema(required: ['first_name', 'last_name', 'gender', 'date_of_birth', 'phone']),
            ])
        ),
        responses: [
            new OA\Response(
                response: 201,
                description: 'Patient registered',
                content: new OA\JsonContent(allOf: [
                    new OA\Schema(ref: '#/components/schemas/SuccessEnvelope'),
                    new OA\Schema(properties: [
                        new OA\Property(property: 'data', ref: '#/components/schemas/Patient'),
                    ]),
                ])
            ),
            new OA\Response(ref: '#/components/responses/Unauthenticated', response: 401),
            new OA\Response(ref: '#/components/responses/Forbidden', response: 403),
            new OA\Response(ref: '#/components/responses/ValidationError', response: 422),
        ]
    )]
    public function store(): void
    {
    }

    #[OA\Put(
        path: '/patients/{id}',
        summary: 'Update a patient (partial)',
        description: 'Role: receptionist only. Send only the fields that changed.',
        tags: ['Patients'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer')),
        ],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(ref: '#/components/schemas/PatientInput')
        ),
        responses: [
            new OA\Response(
                response: 200,
                description: 'Patient updated',
                content: new OA\JsonContent(allOf: [
                    new OA\Schema(ref: '#/components/schemas/SuccessEnvelope'),
                    new OA\Schema(properties: [
                        new OA\Property(property: 'data', ref: '#/components/schemas/Patient'),
                    ]),
                ])
            ),
            new OA\Response(ref: '#/components/responses/Unauthenticated', response: 401),
            new OA\Response(ref: '#/components/responses/Forbidden', response: 403),
            new OA\Response(ref: '#/components/responses/NotFound', response: 404),
            new OA\Response(ref: '#/components/responses/ValidationError', response: 422),
        ]
    )]
    public function update(): void
    {
    }

    #[OA\Delete(
        path: '/patients/{id}',
        summary: 'Delete a patient (soft delete)',
        description: 'Role: receptionist only. The record is hidden, not erased. Existing appointments keep showing the patient.',
        tags: ['Patients'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer')),
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Deleted',
                content: new OA\JsonContent(properties: [
                    new OA\Property(property: 'success', type: 'boolean', example: true),
                    new OA\Property(property: 'message', type: 'string', example: 'Patient deleted'),
                    new OA\Property(property: 'data', type: 'null', nullable: true),
                ])
            ),
            new OA\Response(ref: '#/components/responses/Unauthenticated', response: 401),
            new OA\Response(ref: '#/components/responses/Forbidden', response: 403),
            new OA\Response(ref: '#/components/responses/NotFound', response: 404),
        ]
    )]
    public function destroy(): void
    {
    }
}